# Generated by Django 3.1.7 on 2021-04-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('surname', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('upl_date', models.DateField(auto_now_add=True)),
                ('body', models.FileField(upload_to='media')),
                ('short_desc', models.CharField(blank=True, max_length=200)),
                ('authors', models.ManyToManyField(related_name='books', to='books.Author')),
            ],
        ),
    ]
